package dev.openstream.tv.player.skip

import dev.openstream.tv.addon.Video
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long

/**
 * IMDb → MyAnimeList bridge (owner Round-14 #3: AniSkip never fired because his
 * anime is IMDb-keyed). The mapping ships as a bundled asset generated by
 * `tools/build_anime_map.py` from the community anime-lists projects: Fribb's
 * list gives imdb↔mal (+ which TVDB season a MAL entry is), ScudLee's XML gives
 * the episode offset when several MAL entries share one TVDB season
 * (split-cour) and marks absolute-numbered shows.
 *
 * Everything here is pure so the season/episode arithmetic — the part that
 * skipped the wrong window if wrong — is unit-tested without Android.
 */

/** `tvdbSeason` for entries that follow the show's ABSOLUTE episode order
 *  (one MAL entry spanning many TVDB seasons — Naruto, One Piece). */
const val ABSOLUTE_SEASON = -1

/** One MAL entry of a show: it covers [tvdbSeason]'s episodes after
 *  [episodeOffset] (offset in that season's numbering, or absolute order). */
data class ImdbMalEntry(
    val malId: Long,
    val tvdbSeason: Int,
    val episodeOffset: Int,
)

/** A resolved AniSkip key: the MAL entry + the episode number WITHIN it. */
data class MalEpisode(val malId: Long, val episode: Int)

/**
 * Parse the bundled map: `{"tt123":[[malId,season,offset],…],…}` (season -1 =
 * absolute). Any malformed document parses to empty — a bad asset must mean
 * "no skip button", never a crash. Malformed rows are dropped individually.
 */
fun parseAnimeMap(json: String): Map<String, List<ImdbMalEntry>> = try {
    Json.parseToJsonElement(json).jsonObject.mapValues { (_, rows) ->
        rows.jsonArray.mapNotNull { row ->
            val nums = row.jsonArray
            if (nums.size < 3) return@mapNotNull null
            ImdbMalEntry(
                malId = nums[0].jsonPrimitive.long,
                tvdbSeason = nums[1].jsonPrimitive.long.toInt(),
                episodeOffset = nums[2].jsonPrimitive.long.toInt(),
            )
        }
    }.filterValues { it.isNotEmpty() }
} catch (e: Exception) {
    emptyMap()
}

/**
 * Pick the MAL entry + episode for a (season, episode) of an IMDb-keyed show.
 *
 * Seasonal entries win: the entry for this TVDB season with the largest
 * offset still below the episode (split-cour seasons stack by offset).
 * Otherwise absolute entries are tried with [absoluteEpisode] — which season 1
 * can default to its own episode number (S1E7 IS absolute 7). Specials
 * (season 0) never resolve: their MAL mapping is genuinely ambiguous, and a
 * wrong guess skips a window in the wrong episode.
 */
fun resolveMalEpisode(
    entries: List<ImdbMalEntry>,
    season: Int,
    episode: Int,
    absoluteEpisode: Int?,
): MalEpisode? {
    if (season <= 0 || episode <= 0) return null
    entries
        .filter { it.tvdbSeason == season && episode > it.episodeOffset }
        .maxByOrNull { it.episodeOffset }
        ?.let { return MalEpisode(it.malId, episode - it.episodeOffset) }
    val absolute = absoluteEpisode ?: episode.takeIf { season == 1 } ?: return null
    return entries
        .filter { it.tvdbSeason == ABSOLUTE_SEASON && absolute > it.episodeOffset }
        .maxByOrNull { it.episodeOffset }
        ?.let { MalEpisode(it.malId, absolute - it.episodeOffset) }
}

/**
 * The 1-based position of (season, episode) in the show's air order, counting
 * regular seasons only (specials don't advance absolute numbering). Null when
 * the episode isn't in [videos] — better no skip button than a shifted one.
 */
fun absoluteEpisodeNumber(videos: List<Video>, season: Int, episode: Int): Int? {
    val ordered = videos
        .filter { (it.season ?: 0) > 0 && it.episode != null }
        .sortedWith(compareBy({ it.season }, { it.episode }))
    val index = ordered.indexOfFirst { it.season == season && it.episode == episode }
    return if (index >= 0) index + 1 else null
}
